AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Store and reply to user messages.

Resources:

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      TracingEnabled: true

  StoreAndReplyAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 1024
      Timeout: 10
      CodeUri: .
      Tracing: Active
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
        #Type: Canary10Percent5Minutes
        #Type: Linear10PercentEvery1Minute
        Alarms:
          - !Ref AliasErrorMetricGreaterThanZeroAlarm
          - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
        - Statement:
          - Effect: Allow
            Action:
              - 'comprehend:DetectDominantLanguage'
              - 'translate:TranslateText'
            Resource: '*'
        - Statement:
          - Effect: "Allow"
            Action:
              - "cloudwatch:putMetricData"
            Resource: "*"
      Environment:
        Variables:
          MESSAGES_TABLE: !Ref MessagesTable
          REPLY_MESSAGE: 'Good Afternoon Amsterdam! Message submitted via API'
          REPLY_LANGUAGE: 'nl'
          METRIC_NAMESPACE: !Ref AWS::StackName
          METRIC_DIMENSION_NAME: 'Interface'
          METRIC_DIMENSION_VALUE: 'API'
          METRIC_NAME: 'Message Chars'
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /send
            Method: GET
            RestApiId: !Ref MyApi

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: 'PAY_PER_REQUEST'
      AttributeDefinitions:
        - AttributeName: 'user'
          AttributeType: 'S'
        - AttributeName: 'timestamp'
          AttributeType: 'N'
      KeySchema:
        - AttributeName: 'user'
          KeyType: 'HASH'
        - AttributeName: 'timestamp'
          KeyType: 'RANGE'

  AliasErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${StoreAndReplyAPIFunction}:live"
        - Name: FunctionName
          Value: !Ref StoreAndReplyAPIFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

  LatestVersionErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${StoreAndReplyAPIFunction}:live"
        - Name: FunctionName
          Value: !Ref StoreAndReplyAPIFunction
        - Name: ExecutedVersion
          Value: !GetAtt StoreAndReplyAPIFunction.Version.Version
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

Outputs:
    StoreAndReplyAPI:
      Description: "API Gateway endpoint URL for Prod stage for StoreAndReplyAPI function"
      Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/send/"
